apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aic-transparency.fullname" . }}
  labels:
    {{- include "aic-transparency.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aic-transparency.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aic-transparency.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      {{- if .Values.sampledata.enabled }}
      - name: install-demo-data
        image: {{ .Values.sampledata.image }}
        command: [ 'sh', '-c', 
          'echo "copy scenario data to pod volume";
          cp -v -r /scenariodata/data_structures /target;
          ']
        volumeMounts:
          - name: scenariodata
            mountPath: /target
      {{- end }}         
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote }}
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.app.context_path | quote }}
            - name: APP_SERVICE_URI
              value: {{ .Values.app.service_uri }}
            - name: COCKPIT_HOSTNAME
              value: {{ .Values.app.cockpit.hostname }}
            - name: COCKPIT_MODULEAPI
              value: {{ .Values.app.cockpit.moduleapi }}
            - name: COCKPIT_AICAPI
              value: {{ .Values.app.cockpit.aicapi }}
            {{- if .Values.sampledata.enabled }}
            - name: SCENARIO_SETUP
              value: "true"
            - name: SCENARIO_IMPORTFOLDER
              value: /scenariodata/data_structures/{{ .Values.sampledata.importFolder }}-{{ .Values.sampledata.language }}
            {{- end }}                       
            {{- if .Values.auth.enabled }}
            - name: COCKPIT_AUTH_URL
              value: {{ .Values.auth.auth_url }}
            - name: COCKPIT_AUTH_CLIENT_ID
              value: {{ .Values.auth.client_id }}
            - name: COCKPIT_AUTH_USERNAME
              value: {{ .Values.auth.username }}
            - name: COCKPIT_AUTH_PASSWORD
              value: {{ .Values.auth.password }}
            {{- else }}
            - name: SPRING_PROFILES_ACTIVE
              value: default
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.sampledata.enabled }}              
          volumeMounts:
            - name: scenariodata
              mountPath: /scenariodata
          {{- end }}              
          livenessProbe:
            httpGet:
              path: {{ .Values.app.context_path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.app.context_path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.sampledata.enabled }}
      volumes:
        - name: scenariodata
          emptyDir: {}
      {{- end }}            
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
