name: test-tapi

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-08-29T01-40-52Z
  command: server --console-address ":9001" http://minio1/data{1...2}
  expose:
    - "9000"
    - "9001"
  ports:
      - "9000:9000"
      - "9001:9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ai-cockpit
      POSTGRES_USER: ai-cockpit
      POSTGRES_PASSWORD: ai-cockpit
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ai-cockpit']
      interval: 5s
      timeout: 60s
      retries: 30
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #      - pgadmin:/var/lib/pgadmin
  #      - ./pgadmin/postgreslocal-servers-config.json:/pgadmin4/servers.json
  #   ports:
  #     - "5050:80"

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  createbuckets:
    image: minio/mc
    depends_on:
      minio1:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio1:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/anomalies;
      /usr/bin/mc policy set public myminio/anomalies;
      exit 0;
      "  

  ai-cockpit:
    image: starwitorg/ai-cockpit:1.0.7
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ai-cockpit
      MINIO_USER: minioadmin
      MINIO_PASSWORD: minioadmin
      MINIO_ENDPOINT: http://minio1:9000
      SBOM_ENABLED: true
    ports:
      - "8081:8081"

  # simulates hosting of sboms
  sbom-host:
    image: httpd:latest
    ports:
    - '1080:80'
    volumes:
    - ./static-content:/usr/local/apache2/htdocs

  sbom-generator:
    image: starwitorg/sbom-generator:0.0.10
    environment:
      SERVER_PORT: 8082
    network_mode: host
      
volumes:
  db:
  pgadmin:
  data1-1:
  data1-2: