replicaCount: 1

image:
  repository: starwitorg/starwit-aicapi-transparency
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${project.version}

app:
  context_path: "/aic-transparency"

auth:
  enabled: false
  keycloak_url: https://hostname/realms/aicockpit
  client_id: aicockpit
  client_secret: aicockpit 

service:
  port: 8080

ingress:
  enabled: false
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: aic.starwit-infra.de
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: aic.starwit-infra.de
      hosts:
        - spc.data-wolfsburg.de

resources:
  limits:
    memory: "500Mi"

