replicaCount: 1

image:
  repository: starwitorg/starwit-aicapi-transparency
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${project.version}

app:
  context_path: "/aic-transparency"
  # This is necessary as service cannot figure out, which endpoint is actually used (proxies et al)
  service_uri: http://localhost:8080
  cockpit:
    hostname: http://ai-cockpit.aic.svc.cluster.local:8080
    moduleapi: "api/module"
    aicapi: "api/aic/modules"

  minio:
    endpoint: http://localhost:9000
    username: minioadmin
    password: minioadmin
    bucket: sboms

auth:
  enabled: false
  auth_url: https://hostname/realms/aicockpit/protocol/openid-connect/token
  client_id: aicockpit
  username: apiuser
  password: apiuser


sampledata:
  enabled: false
  image: starwitorg/ai-cockpit-sampledata:latest
  importFolder: traffic
  language: en

service:
  port: 8080

ingress:
  enabled: false
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: aic.starwit-infra.de
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: aic.starwit-infra.de
      hosts:
        - spc.data-wolfsburg.de

resources:
  limits:
    memory: "500Mi"

autoscaling:
  enabled: false

